export let zodiacSigns = [
    {
        id: 1,
        aztroYesterday: "?sign=aries&day=yesterday",
        aztroToday: "?sign=aries&day=today",
        aztroTomorrow: "?sign=aries&day=tomorrow",
        signName: "Aries",
        signSymbol: "♈",
        signDescription: "Aries people tend to be energetic, forceful and outgoing. They are good at getting things done, although they prefer starting to finishing. They move into the world in a headstrong, pioneering way.",
        signDate: "March 21 - April 19",
        signImg: "img/signs/sign-aries.png",
        planetName: "Mars",
        planetDescription: "Mars is the planet of outward activity and animal passion. When strong in the chart it can indicate a volatile temper, and also great courage.",
        planetSymbol: "♂",
        elementName: "Fire",
        elementSymbol: "🜂",
        elementDescription: "Fire is a radiant form of energy that brings light to the world around it, enthusiastic and excitable, self-oriented, impatient and essentially optimistic. Fire people are honest to a fault, freedom loving and often insist on their own point of view.",
        gemName: "Diamond",
        gemDescription: "The Aries birthstone is the Diamond. The Diamond is a solid form of carbon and is one of the most sought-after gemstones in the world. The diamond means clarity, truth, and vision.",
        month1:3,
        month2:4,
        day1:21,
        day2:19,
    },

    {
        id: 2,
        aztroYesterday: "?sign=taurus&day=yesterday",
        aztroToday: "?sign=taurus&day=today",
        aztroTomorrow: "?sign=taurus&day=tomorrow",
        signName: "Taurus",
        signSymbol: "♉",
        signDescription: "Taureans crave the security and comfort of relaxing in the warmth of their home environment. They value the senses and the enjoyment of material things. Taureans are likely to work hard to make their home an attractive one.",
        signDate: "April 20 - May 20",
        signImg: "img/signs/sign-tauro.png",
        planetName: "Venus",
        planetDescription: "Venus is the planet of love and relationship. Its position in the chart indicates the area in which the give and take of love, affection and sensual pleasure will be expressed.",
        planetSymbol: "♀",
        elementName: "Earth",
        elementSymbol: "🜃",
        elementDescription: "The Earth energy is grounded and heavy, responding to the gravity of physical circumstances and limitations. Earth people are in touch with their bodies and the pleasures of the physical world around them. They are givers of form and structure.",
        gemName: "Emerald",
        gemDescription: "The Emerald is a green precious gem that means peace and prosperity. It is said to bring emotional well-being and bestow emotional strength to the stubborn Taurus.",
        month1: 4,
        month2: 5,
        day1: 20,
        day2: 21,
    },

    {
        id: 3,
        aztroYesterday: "?sign=gemini&day=yesterday",
        aztroToday: "?sign=gemini&day=today",
        aztroTomorrow: "?sign=gemini&day=tomorrow",
        signName: "Gemini",
        signSymbol: "♊",
        signDescription: "Is the sign associated with communication, logical thought processes (based on duality) and the conscious mind. Gemini tend to be airy and intellectual, glib of tongue and curious about life and other people.",
        signDate: "May 21 - June 20",
        signImg: "img/signs/sign-geminis.png",
        planetName: "Mercury",
        planetDescription: "Mercury represents the mind and intellect, is an airy planet, associated with all forms of communication and the in-flow and out-flow of intelligence. Its position indicates how your mental function will be expressed, and where techniques and skills are available to you.",
        planetSymbol: "☿",
        elementName: "Air",
        elementSymbol: "🜁",
        elementDescription: "Air people tend to live in their heads, being logical and scientific, as well as curious about what is around them and detached in their outlook.",
        gemName: "Pearl",
        gemDescription: "It symbolizes the duality in the zodiac sign. It represents joy and sorrow, life and death, and health and sickness. Pearls also represent the person’s spiritual journey that is deep-rooted in this sign.",
        month1: 5,
        month2: 6,
        day1: 21,
        day2: 20,
    },

    {
        id: 4,
        aztroYesterday: "?sign=cancer&day=yesterday",
        aztroToday: "?sign=cancer&day=today",
        aztroTomorrow: "?sign=cancer&day=tomorrow",
        signName: "Cancer",
        signSymbol: "♋",
        signDescription: "Cancerians are nurturing and protective of others. They may appear passive, and tend to rely on their feelings to make decisions. They are subtle, rather than direct, and are likely to reflect the moods of those around them.",
        signDate: "June 21 - July 22",
        signImg: "img/signs/sign-cancer.png",
        planetName: "The Moon",
        planetDescription: "The Moon represents the personal self, the feelings and the unconscious. It is a reflection of the true self, represented by the Sun. The Moon also stands for security and instinctual or habitual patterns, as well as the ability to relate to others, and to be nurturing to others.",
        planetSymbol: "☽",
        elementName: "Water",
        elementSymbol: "🜄",
        elementDescription: "Receptive and sensitive to subtle currents of interconnection, it flows through everything and connects at a deeper and more unconscious level than that provided by logical thought. Water people are tuned in to a deeper and subtler reality than other types around them.",
        gemName: "Ruby",
        gemDescription: "Ruby is a superb birthstone with a dazzling color in different shades. Its color radiates intensely the same way that its energy does, stimulating passion and vitality for life.",
        month1: 6,
        month2: 7,
        day1: 21,
        day2: 22,
    },
    
    {
        id: 5,
        aztroYesterday: "?sign=leo&day=yesterday",
        aztroToday: "?sign=leo&day=today",
        aztroTomorrow: "?sign=leoies&day=tomorrow",
        signName: "Leo",
        signSymbol: "♌",
        signDescription: "Leos are likely to express themselves in dramatic, creative and assertive ways. Leos have great energy, courage and honesty, they can be quite determined and usually get their way when they really want to.",
        signDate: "July 23 - August 22",
        signImg: "img/signs/sign-leo.png",
        planetName: "The Sun",
        planetDescription: "The Sun represents the Self, one's way of being in the world. It can represent, on different levels, both the ego and the higher Self or soul purpose.",
        planetSymbol: "☉",
        elementName: "Fire",
        elementSymbol: "🜂",
        elementDescription: "Fire is a radiant form of energy that brings light to the world around it, enthusiastic and excitable, self-oriented, impatient and essentially optimistic. Fire people are honest to a fault, freedom loving and often insist on their own point of view.",
        gemName: "Peridot",
        gemDescription: "Peridot can potentially have a huge influence on the wearer’s character. As it renders an impact on the individual, it also helps him play a vital role in the shaping up of society at large.",
        month1: 7,
        month2: 8,
        day1: 23,
        day2: 22,
    },

    {
        id: 6,
        aztroYesterday: "?sign=virgo&day=yesterday",
        aztroToday: "?sign=virgo&day=today",
        aztroTomorrow: "?sign=virgo&day=tomorrow",
        signName: "Virgo",
        signSymbol: "♍",
        signDescription: "Virgo people tend to be very conscious of details. They are likely to be neat and orderly, at least in some area of their life, although they may exhibit the opposite tendency in cases where they have not yet found their guiding principle of organization.",
        signDate: "August 23 - September 22",
        signImg: "img/signs/sign-virgo.png",
        planetName: "Mercury",
        planetDescription: "Mercury represents the mind and intellect. Mercury is an airy planet, associated with all forms of communication and the in-flow and out-flow of intelligence. Its position indicates how your mental function will be expressed, and where techniques and skills are available to you.",
        planetSymbol: "☿",
        elementName: "Earth",
        elementSymbol: "🜃",
        elementDescription: "The Earth energy is grounded and heavy, responding to the gravity of physical circumstances and limitations. Earth people are in touch with their bodies and the pleasures of the physical world around them. They are givers of form and structure.",
        gemName: "Green Jade",
        gemDescription: "Jade brings harmony in the mind, body, and soul, bringing vitality to the health conscious and soul searcher side of Virgos.",
        month1: 8,
        month2: 9,
        day1: 23,
        day2: 22,
    },
    
    {
        id: 7,
        aztroYesterday: "?sign=libra&day=yesterday",
        aztroToday: "?sign=libra&day=today",
        aztroTomorrow: "?sign=libra&day=tomorrow",
        signName: "Libra",
        signSymbol: "♎",
        signDescription: "Libra is the sign of harmony and relationship. Librans are known for their good taste, elegance and charm. They are seekers of harmony and beauty. Intimate relationships are quite important to them, as are issues of social justice.",
        signDate: "September 23 - October 22",
        signImg: "img/signs/sign-libra.png",
        planetName: "Venus",
        planetDescription: "Venus is the planet of love and relationship. Its position in the chart indicates the area in which the give and take of love, affection and sensual pleasure will be expressed.",
        planetSymbol: "♀",
        elementName: "Air",
        elementSymbol: "🜁",
        elementDescription: "Air people tend to live in their heads, being logical and scientific, as well as curious about what is around them and detached in their outlook.",
        gemName: "Lapis Lazuli",
        gemDescription: "This birthstone for Libra centers around the air element, helping you go into a more profound reflection, access your intuition, and achieve serenity. For Libras who don’t care for confrontations, Lapis Lazuli guarantees peace of mind and genuine feelings of serenity.",
        month1: 9,
        month2: 10,
        day1: 23,
        day2: 22,
    },

    {
        id: 8,
        aztroYesterday: "?sign=scorpio&day=yesterday",
        aztroToday: "?sign=scorpio&day=today",
        aztroTomorrow: "?sign=scorpio&day=tomorrow",
        signName: "Scorpio",
        signSymbol: "♏",
        signDescription: "Scorpio is the most intense sign of the Zodiac, and is associated with sexual activity and with the symbolism of death and rebirth. Their emotions run deep. Scorpios have great personal magnetism and great powers of persuasion or even the ability to coerce others.",
        signDate: "October 23 - November 21",
        signImg: "img/signs/sign-escorpio.png",
        planetName: "Pluto",
        planetDescription: "Pluto is a force for change that can be destructive in its power. Pluto is related to will, and intense passion, and has a reputation for ruthlessness.",
        planetSymbol: "♇",
        elementName: "Water",
        elementSymbol: "🜄",
        elementDescription: "Receptive and sensitive to subtle currents of interconnection, it flows through everything and connects at a deeper and more unconscious level than that provided by logical thought. Water people are tuned in to a deeper and subtler reality than other types around them.",
        gemName: "Topaz",
        gemDescription: "It helps in the purification and refinement of the animal nature and lifts the powers to a higher plane of expression. It rules on the lower nature and causes Scorpios to achieve more significant power.",
        month1: 10,
        month2: 11,
        day1: 23,
        day2: 21,
    },
    
    {
        id: 9,
        aztroYesterday: "?sign=sagittarius&day=yesterday",
        aztroToday: "?sign=sagittarius&day=today",
        aztroTomorrow: "?sign=sagittarius&day=tomorrow",
        signName: "Sagittarius",
        signSymbol: "♐",
        signDescription: "Sagittarius is an optimistic, positive-thinking sign associated with the quest for freedom from all restriction as well as idealism, religion and philosophy. Sagittarians are direct and forthright, good-natured and affirmative in their outlook.",
        signDate: "November 22 - December 21",
        signImg: "img/signs/sign-sagitario.png",
        planetName: "Jupiter",
        planetDescription: "Jupiter is the planet of faith, positivism and optimism. Jupiter represents the principle of expansion, versus contraction (as represented by Saturn) and the aspirations of the higher self.",
        planetSymbol: "♃",
        elementName: "Fire",
        elementSymbol: "🜂",
        elementDescription: "Fire is a radiant form of energy that brings light to the world around it, enthusiastic and excitable, self-oriented, impatient and essentially optimistic. Fire people are honest to a fault, freedom loving and often insist on their own point of view.",
        gemName: "Blue Topaz",
        gemDescription: "It’s a stone that signifies love and affection. It’s known for its associated characteristics of strength, tenacity, dedication, resilience and great sense. This Sagittarius birthstone is believed to balance emotions and thoughts for a harmonious lifestyle.",
        month1: 11,
        month2: 12,
        day1: 22,
        day2: 21,
    },

    {
        id: 10,
        aztroYesterday: "?sign=capricorn&day=yesterday",
        aztroToday: "?sign=capricorn&day=today",
        aztroTomorrow: "?sign=capricorn&day=tomorrow",
        signName: "Capricorn",
        signSymbol: "♑",
        signDescription: "Capricorn people are ambitious and practical, and are likely to have an excellent sense of social responsibility. They also tend to be conscious of social mores, perhaps to the point of over-concern. Their natural caution allows them to advance slowly and steadily to the top.",
        signDate: "December 22 - January 19",
        signImg: "img/signs/sign-capricornio.png",
        planetName: "Saturn",
        planetDescription: "Saturn is the planet of limitation and contraction, and the trials of life experience. This includes discipline, punctuality, and the conservation of material resources.",
        planetSymbol: "♄",
        elementName: "Earth",
        elementSymbol: "🜃",
        elementDescription: "The Earth energy is grounded and heavy, responding to the gravity of physical circumstances and limitations. Earth people are in touch with their bodies and the pleasures of the physical world around them. They are givers of form and structure.",
        gemName: "Garnet",
        gemDescription: "Garnet’s meaning is commitment and creativity. Are said to attract the energy of planet Saturn, the ruling planet of Capricorns, helping those who wear it prosper and lead a more aligned lifestyle – mentally, spiritually and physically.",
        month1: 12,
        month2: 1,
        day1: 22,
        day2: 19,
    },
    
    {
        id: 11,
        aztroYesterday: "?sign=aquarius&day=yesterday",
        aztroToday: "?sign=aquarius&day=today",
        aztroTomorrow: "?sign=aquarius&day=tomorrow",
        signName: "Aquarius",
        signSymbol: "♒",
        signDescription: "Aquarians have a rebellious nature, and are eccentric, spontaneous and original. They are forward thinking and detached, and can seem conservative though they really are not very much so. They are scientifically minded and logical, and confident in manner.",
        signDate: "January 20 - February 18",
        signImg: "img/signs/sign-acuario.png",
        planetName: "Uranus",
        planetDescription: "Uranus is the planet of freedom and revolutionary vision, the urge for change and the ability to visualize new possibilities. It is also associated with mental studies, electricity and astrology.",
        planetSymbol: "♅",
        elementName: "Air",
        elementSymbol: "🜁",
        elementDescription: "Air people tend to live in their heads, being logical and scientific, as well as curious about what is around them and detached in their outlook.",
        gemName: "Amethyst",
        gemDescription: "It's a natural sedative that calms anxiety, alleviates irritability, balances mood swings, and dispels outrage, anger, dread, and nervousness. It additionally mitigates despondency and misery and all traces of pessimism or negativity.",
        month1: 1,
        month2: 2,
        day1: 20,
        day2: 18,
    },

    {
        id: 12,
        aztroYesterday: "?sign=pisces&day=yesterday",
        aztroToday: "?sign=pisces&day=today",
        aztroTomorrow: "?sign=pisces&day=tomorrow",
        signName: "Pisces",
        signSymbol: "♓",
        signDescription: "Pisces is a watery sign, concerned with subtle emotions and secret mystical depths. Are dreamy and full of imagination, and are easily influenced by everything around them, being quite sensitive to the emotions of others.",
        signDate: "February 19 - March 20",
        signImg: "img/signs/sign-piscis.png",
        planetName: "Neptune",
        planetDescription: "Neptune represents the universal ocean of oneness with all beings. It is thus highly compassionate, also idealistic, imaginative and self login or even self undoing, and can be associated with drugs or media, as fantasy expressions.",
        planetSymbol: "♆",
        elementName: "Water",
        elementSymbol: "🜄",
        elementDescription: "Receptive and sensitive to subtle currents of interconnection, it flows through everything and connects at a deeper and more unconscious level than that provided by logical thought. Water people are tuned in to a deeper and subtler reality than other types around them.",
        gemName: "Aquamarine",
        gemDescription: "Aquamarine is believed to give its wearer foresight and clairvoyance, as well as enhance intelligence.",
        month1: 2,
        month2: 3,
        day1: 19,
        day2: 20,
    },
]

